New patches as for 2 april 2020

diff --git a/cinelerra-goodguy.SlackBuild b/cinelerra-goodguy.SlackBuild
--- a/cinelerra-goodguy.SlackBuild
+++ b/cinelerra-goodguy.SlackBuild
@@ -22,9 +22,11 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+LANG=C
+
 PRGNAM=cinelerra-goodguy
 VERSION="$( date +%Y%m%d )"
-BUILD=${BUILD:-22}
+BUILD=${BUILD:-31}
 TAG=${TAG:-_cin}
 
 if [ -z "$ARCH" ]; then
@@ -42,7 +44,7 @@ OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i486" ]; then
   #SLKCFLAGS="-O3 -march=i686 -mtune=i686"
-  SLKCFLAGS="-O3 -ffast-math -mavx -march=native -mtune=native"
+  SLKCFLAGS="-O3 -ffast-math -mavx -march=native -mtune=native -fopenmp"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O3 -march=i686 -mtune=i686"
@@ -62,7 +64,9 @@ rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
-git clone --depth 1 git://git.cinelerra-gg.org/goodguy/cinelerra.git $PRGNAM-$VERSION
+#git clone --depth 1 git://git.cinelerra-gg.org/goodguy/cinelerra.git $PRGNAM-$VERSION
+
+cp -aR $CWD/new-git/cinelerra/ $TMP/$PRGNAM-$VERSION
 
 # tmp hack
 # cd $PRGNAM-$VERSION
@@ -72,15 +76,20 @@ git clone --depth 1 git://git.cinelerra-gg.org/goodguy/cinelerra.git $PRGNAM-$VE
 # cd ../
 
 cd $PRGNAM-$VERSION/cinelerra-5.1
+git pull
 chown -R root:root .
 
 git apply -v $CWD/x11_nonstd_prefix_compile_fixes.diff
-git apply -v $CWD/cinelerra_dir_fixes_3.diff
+git apply -v $CWD/cinelerra_dir_fixes_4.diff
 git apply -v $CWD/db_compile_fixes.diff
 cat $CWD/dri3_disable_cin51.diff | patch -p0
 #git apply -v $CWD/ffmpeg_disable-doc-building.patch
 #git apply -v $CWD/openexr_pthread_configure_fix.patch
 git apply -v $CWD/force_libvpx.diff
+
+git apply -v $CWD/nasm_thirdparty_2.patch
+#git apply -v $CWD/c11_configure.ac_from_oxr_1.patch
+#git apply -v $CWD/lv2-pkgconfig.patch
 
 cat $CWD/libva_x11r7.diff | patch -p0
 cat $CWD/libvdpau_x11r7.diff | patch -p0
@@ -100,15 +109,47 @@ git apply -v  $CWD/I-only_files_reverse_play_speedup.diff
 #git apply -v $CWD/andrew.patch
 cp $CWD/avi_fix.patch thirdparty/src/ffmpeg.git.patch20
 
-# old gphoto fails opencv build
-git apply -v $CWD/opencv_gphoto2.diff
 
-cat $CWD/x265-mult/Makefile.diff | patch -p1 --verbose || exit 0
+# old gphoto fails opencv build
+#git apply -v $CWD/opencv_gphoto2.diff
+
+git apply -v $CWD/thirdparty_build_trim-full.diff
+
+#moved to dedicated x265 multidepth secction below
+#cat $CWD/x265-mult/Makefile.diff | patch -p1 --verbose || exit 0
+
+
+#git apply -v  $CWD/filepng_16_bit_real_fix-II.diff
+
+# tmp libaom update
+rm thirdparty/src/libaom-v1.0.0.tar.xz
+cp $CWD/libaom-v1.0.0.tar.xz thirdparty/src/
+
+# nasm
+cp $CWD/nasm-2.14.02.tar.xz thirdparty/src
+
+# lame patches
+cp $CWD/lame-3.100-fastcrc.diff thirdparty/src/lame-3.100.patch1
+#cp $CWD/lame-3.100-sse-20171014.diff thirdparty/src/lame-3.100.patch2
+git apply -v $CWD/lame-make-opt-after-th.diff
+
+git apply -v $CWD/openCV4-static-gcc5_more-disable-3.diff
+#git apply $CWD/TIFF-2.diff
+
+#x265 multidepth .a lib
+cp $CWD/x265_3.2.1.patch1 thirdparty/src
+cp $CWD/x265_3.2.1.patch2 thirdparty/src
+cp $CWD/x265_3.2.1.patch3 thirdparty/src
+git apply -v $CWD/x265_makefile-2.patch
+
+# tmp fix for boxblur plugin
+git apply -v $CWD/boxblur_32bit_tmp_fix.diff
 
 # temporariry remove ffmpeg.git patch #2
 # mv thirdparty/src/ffmpeg.git.patch2 thirdparty/src/NO_patch
 #add new patch from  Marton Balint
 # cp $CWD/ffmpeg_ts-branch1.patch thirdparty/src/ffmpeg.git.patch2
+#mv thirdparty/src/ffmpeg.git.patch9 thirdparty/src/__mpeg.git.patch9
 
 # configure the build
 ./autogen.sh
@@ -125,8 +166,8 @@ export CC="ccache gcc"
 #    --with-git-ffmpeg=https://git.ffmpeg.org/ffmpeg.git \
 
 
-EXTRA_LIBS=" -lOpenCL -ldav1d -lxvidcore -lass -lbluray" \
-FFMPEG_EXTRA_CFG=" --enable-opencl --enable-libdav1d --enable-libxvid --enable-libass --enable-libbluray" \
+EXTRA_LIBS=" -lOpenCL -ldav1d -lxvidcore -lass -lbluray -lsnappy" \
+FFMPEG_EXTRA_CFG=" --enable-opencl --enable-libdav1d --enable-libxvid --enable-libass --enable-libbluray --enable-libsnappy" \
 CFLAGS="$SLKCFLAGS -D__STDC_CONSTANT_MACROS" \
 CXXFLAGS="$SLKCFLAGS -D__STDC_CONSTANT_MACROS" \
 LDFLAGS="-L/usr/X11R7/lib -ldl -L/usr/lib${LIBDIRSUFFIX}" \
@@ -136,10 +177,10 @@ LDFLAGS="-L/usr/X11R7/lib -ldl -L/usr/lib${LIBDIRSUFFIX}" \
     --with-opencv=sta,tar=https://cinelerra-gg.org/download/opencv/opencv-20180401.tgz \
     --sysconfdir=/etc \
     --localstatedir=/var \
-    --libdir=/usr/lib \
+    --libdir=/usr/lib${LIBDIRSUFFIX} \
     --with-ladspa-build \
     --with-opus \
-    --without-nv \
+    --with-nv \
     --enable-opus \
     --with-jobs=4 \
     --with-booby \
@@ -153,15 +194,16 @@ LDFLAGS="-L/usr/X11R7/lib -ldl -L/usr/lib${LIBDIRSUFFIX}" \
 
 #cd  $TMP/$PRGNAM-$VERSION/cinelerra-5.1/thirdparty/x264-snapshot-20180118-2245
 
-cp $CWD/lavf.c.patch1  src/x264-snapshot-20180118-2245.patch2
-cp $CWD/x264-git.patch2 src/x264-snapshot-20180118-2245.patch3
-cp $CWD/x264-git.patch3 src/x264-snapshot-20180118-2245.patch4
+cp $CWD/lavf.c.patch1  src/x264-snapshot-20191217-2245.patch2
+cp $CWD/x264-git.patch2 src/x264-snapshot-20191217-2245.patch3
+cp $CWD/x264-git.patch3 src/x264-snapshot-20191217-2245.patch4
 
-mkdir x265_3.1.2
-cp $CWD/x265-mult/configure.placebo x265_3.1.2/configure
-cp $CWD/x265-mult/Makefile x265_3.1.2/
-cp $CWD/x265-mult/multilib_root.sh x265_3.1.2/multilib.sh
-cp $CWD/x265-mult/multilib.sh.diff src/x265_3.1.2.patch1
+#superseeded by above
+#mkdir x265_3.2.1
+#cp $CWD/x265-mult/configure.placebo x265_3.2.1/configure
+#cp $CWD/x265-mult/Makefile x265_3.2.1/
+#cp $CWD/x265-mult/multilib_root.sh x265_3.2.1/multilib.sh
+#cp $CWD/x265-mult/multilib.sh.diff src/x265_3.2.1.patch1
 
 #cat $CWD/lavf.c.patch | patch -R -v -p1
 #cat $CWD/x264-revert-1.diff | patch -R -v -p1
